export const LEARN_CONTENT_TYPES = [
	"topic",
	"lesson",
	"guide",
	"reference",
	"case-study",
	"historical-record",
] as const;

export const LEARN_STATUSES = ["available", "archived", "planned"] as const;

export const LEARN_PRESENTATIONS = [
	"standard",
	"reference",
	"case-study",
	"historical-record",
] as const;

export type LearnContentType = (typeof LEARN_CONTENT_TYPES)[number];
export type LearnStatus = (typeof LEARN_STATUSES)[number];
export type LearnPresentation = (typeof LEARN_PRESENTATIONS)[number];

export interface LearnMetadata {
	topic: string;
	order: number;
	contentType: LearnContentType;
	label: string;
	historical: boolean;
	status: LearnStatus;
	presentation: LearnPresentation;
}

export interface LearnTopicDefinition {
	label: string;
	description: string;
}

export type LearnTopicRegistry = Record<string, LearnTopicDefinition>;

export const learnTopicRegistry = {
	fork: {
		label: "Fork",
		description:
			"Understand what triggers an Augur fork, how it works, and what REP holders need to know.",
	},
} as const satisfies LearnTopicRegistry;

export interface LearnTopicContext extends LearnTopicDefinition {
	key: string;
	path: string;
}

export interface LearnEntryLike {
	slug: string;
	data: LearnMetadata;
}

export interface LearnNavigationItem {
	label: string;
	path: string;
	order: number;
	contentType: LearnContentType;
	historical: boolean;
	status: LearnStatus;
}

export type LearnEntryGroup = "core" | "case-study" | "historical-record";

export interface LearnTopicCatalogItem {
	topic: LearnTopicContext;
	entries: LearnNavigationItem[];
	availableEntries: LearnNavigationItem[];
	archivedEntries: LearnNavigationItem[];
}

export function getLearnTopic(
	topicKey: string,
	registry: LearnTopicRegistry = learnTopicRegistry,
): LearnTopicContext {
	const definition = registry[topicKey];

	if (!definition) {
		throw new Error(`Unknown Learn topic: ${topicKey}`);
	}

	return {
		key: topicKey,
		path: `/learn/${topicKey}/`,
		...definition,
	};
}

export function getLearnEntryPath(slug: string): string {
	const normalizedSlug = slug.replace(/^\/+|\/+$/gu, "").replace(/\/index$/u, "");
	return `/learn/${normalizedSlug}/`;
}

export function assertLearnEntries(
	entries: readonly LearnEntryLike[],
	registry: LearnTopicRegistry = learnTopicRegistry,
): void {
	const orders = new Map<string, Set<number>>();

	for (const entry of entries) {
		getLearnTopic(entry.data.topic, registry);

		const routeTopic = entry.slug.split("/")[0];
		if (routeTopic !== entry.data.topic) {
			throw new Error(
				`Learn entry ${entry.slug} must be routed under topic ${entry.data.topic}`,
			);
		}

		if (!Number.isInteger(entry.data.order) || entry.data.order < 0) {
			throw new Error(
				`Learn entry ${entry.slug} must have a non-negative integer order`,
			);
		}

		const topicOrders = orders.get(entry.data.topic) ?? new Set<number>();
		if (topicOrders.has(entry.data.order)) {
			throw new Error(
				`Learn topic ${entry.data.topic} has duplicate order ${entry.data.order}`,
			);
		}
		topicOrders.add(entry.data.order);
		orders.set(entry.data.topic, topicOrders);
	}
}

export function getLearnNavigation(
	entries: readonly LearnEntryLike[],
	topicKey: string,
): LearnNavigationItem[] {
	return entries
		.filter(
			(entry) =>
				entry.data.topic === topicKey && entry.data.status !== "planned",
		)
		.sort((left, right) => left.data.order - right.data.order)
		.map((entry) => ({
			label: entry.data.label,
			path: getLearnEntryPath(entry.slug),
			order: entry.data.order,
			contentType: entry.data.contentType,
			historical: entry.data.historical,
			status: entry.data.status,
		}));
}

export function assertLearnTopicLandingEntry(
	topic: LearnTopicContext,
	availableEntries: readonly LearnNavigationItem[],
): void {
	const hasLandingEntry = availableEntries.some(
		(entry) => entry.contentType === "topic" && entry.path === topic.path,
	);

	if (!hasLandingEntry) {
		throw new Error(
			`Learn topic ${topic.key} has available content but no available topic landing entry at ${topic.path}`,
		);
	}
}

export function getLearnTopicCatalog(
	entries: readonly LearnEntryLike[],
	registry: LearnTopicRegistry = learnTopicRegistry,
): LearnTopicCatalogItem[] {
	assertLearnEntries(entries, registry);

	return Object.keys(registry)
		.map((topicKey) => {
			const topic = getLearnTopic(topicKey, registry);
			const topicEntries = getLearnNavigation(entries, topicKey);
			const availableEntries = topicEntries.filter(
				(entry) => entry.status === "available",
			);

			if (availableEntries.length > 0) {
				// getLearnEntryPath normalizes `topic/index` to the route generated by Astro.
				assertLearnTopicLandingEntry(topic, availableEntries);
			}

			return {
				topic,
				entries: topicEntries,
				availableEntries,
				archivedEntries: topicEntries.filter(
					(entry) => entry.status === "archived",
				),
			};
		})
		.filter(({ availableEntries }) => availableEntries.length > 0);
}

export function getLearnEntryGroup(
	entry: Pick<LearnNavigationItem, "contentType" | "historical">,
): LearnEntryGroup {
	if (entry.contentType === "case-study") {
		return "case-study";
	}

	if (entry.historical || entry.contentType === "historical-record") {
		return "historical-record";
	}

	return "core";
}

export function getLearnPageContext(
	entry: LearnEntryLike,
	entries: readonly LearnEntryLike[],
	registry: LearnTopicRegistry = learnTopicRegistry,
) {
	const topic = getLearnTopic(entry.data.topic, registry);

	return {
		topic,
		navigation: getLearnNavigation(entries, topic.key),
	};
}

export function usesHistoricalPresentation(
	presentation: LearnPresentation,
): boolean {
	return presentation === "historical-record";
}
